### PR TITLE
add io-ts types

### PR DESCRIPTION
**Pull request by gcanti**
@sledorze There's a bunch of types here that we could move to `io-ts-types`, what do you think? (if you are interested in this library of course)

### CODE REVIEW

**Comment by sledorze** [comment]
@gcanti I'm not sure about the implementation of Integer (relying on bounded 'number' looks brittle and  limited to me).
Beside that, yes some types are interesting

**Comment by gcanti** [comment]
> relying on bounded 'number' looks brittle and limited to me

@sledorze what you mean?

**Comment by sledorze** [comment]
@gcanti number can overflow and has limited precision.

**Comment by gcanti** [comment]
Ah right, I'm looking for some big* implementations. These are the best candidates so far

- [big-integer](https://github.com/peterolson/BigInteger.js)
- [big-rational](https://github.com/peterolson/BigRational.js)

By chance do you know any better implementation?

**Comment by sledorze** [comment]
@gcanti we're using big-integer ourselves, we've however not spent too much time looking around for an alternative.

**Comment by gcanti** [comment]
@sledorze master is now based on `big-integer`, let me know what you think about the current implementation

**Pull request merged**
